services:
  server:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "5002:5002"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: pgvector/pgvector:pg17
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: ...          # vector db name
      POSTGRES_USER: postgres   # default pg username
      # use a secrets/db_pwd.txt in prod
      POSTGRES_PASSWORD: ...   # postgresql password
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data: