from fastapi import APIRouter, Depends, HTTPException, status
from src.core.constants import ResponseType
from src.core.log import get_logger
from src.core.utility import clean_llm_output
from src.factory.ai_service_factory import get_ai_service
from src.interface.ai_service import AbstractAIService
from src.schema.ai import Query
from src.schema.response import APIResponse

ai = APIRouter()
logger = get_logger(__name__)


@ai.post("/ai/query", response_model=APIResponse)
async def query_response(
    query: Query, ai_service: AbstractAIService = Depends(get_ai_service)
):
    """
    Handles a direct query to an LLM agent without RAG (Retrieval-Augmented Generation).

    The user's query is added to the session messages, and the response is
    generated by a general-purpose AI model (default: GPT-4o_MINI).
    Calculates and returns the token cost for the interaction.

    Args:
        query: The user's query wrapped in a Query schema object.

    Returns:
        A dictionary with the response status and a message containing the
        AI's reply and the calculated token cost.

    Raises:
        Exception: Catches and reports any general error during the agent invocation.
    """

    try:
        agent_response, cost = await ai_service.interact(user_message=query.query)
        return APIResponse(
            response=ResponseType.SUCCESS,
            message={
                "ai response": clean_llm_output(agent_response),
                "token cost": cost,
            },
        )
    except Exception as e:
        logger.error(f"Error {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Error while processing AI query. Please try again.",
        )
